export const dataTableConfig = {
  textOperators: [
    { label: "Enthält", value: "iLike" as const },
    { label: "Enthält nicht", value: "notILike" as const },
    { label: "Ist", value: "eq" as const },
    { label: "Ist nicht", value: "ne" as const },
    { label: "Ist leer", value: "isEmpty" as const },
    { label: "Ist nicht leer", value: "isNotEmpty" as const },
  ],
  numericOperators: [
    { label: "Ist", value: "eq" as const },
    { label: "Ist nicht", value: "ne" as const },
    { label: "Kleiner als", value: "lt" as const },
    { label: "Kleiner gleich", value: "lte" as const },
    { label: "Größer als", value: "gt" as const },
    { label: "Größer gleich", value: "gte" as const },
    { label: "Zwischen", value: "isBetween" as const },
    { label: "Ist leer", value: "isEmpty" as const },
    { label: "Ist nicht leer", value: "isNotEmpty" as const },
  ],
  dateOperators: [
    { label: "Ist", value: "eq" as const },
    { label: "Ist nicht", value: "ne" as const },
    { label: "Vor", value: "lt" as const },
    { label: "Nach", value: "gt" as const },
    { label: "Am oder vor", value: "lte" as const },
    { label: "Am oder nach", value: "gte" as const },
    { label: "Zwischen", value: "isBetween" as const },
    { label: "Relativ zu heute", value: "isRelativeToToday" as const },
    { label: "Ist leer", value: "isEmpty" as const },
    { label: "Ist nicht leer", value: "isNotEmpty" as const },
  ],
  selectOperators: [
    { label: "Ist", value: "eq" as const },
    { label: "Ist nicht", value: "ne" as const },
    { label: "Ist leer", value: "isEmpty" as const },
    { label: "Ist nicht leer", value: "isNotEmpty" as const },
  ],
  multiSelectOperators: [
    { label: "Hat eines von", value: "inArray" as const },
    { label: "Hat keines von", value: "notInArray" as const },
    { label: "Ist leer", value: "isEmpty" as const },
    { label: "Ist nicht leer", value: "isNotEmpty" as const },
  ],
  booleanOperators: [
    { label: "Ist", value: "eq" as const },
    { label: "Ist nicht", value: "ne" as const },
  ],
  sortOrders: [
    { label: "Aufsteigend", value: "asc" as const },
    { label: "Absteigend", value: "desc" as const },
  ],
  filterVariants: [
    "text",
    "number",
    "range",
    "date",
    "dateRange",
    "boolean",
    "select",
    "multiSelect",
  ] as const,
  operators: [
    "iLike",
    "notILike",
    "eq",
    "ne",
    "inArray",
    "notInArray",
    "isEmpty",
    "isNotEmpty",
    "lt",
    "lte",
    "gt",
    "gte",
    "isBetween",
    "isRelativeToToday",
  ] as const,
  joinOperators: ["and", "or"] as const,
}

export type DataTableConfig = typeof dataTableConfig
